version: '3.7'

services:

    ###########################################################################
    #######                  DB SERVICES                                #######
    ###########################################################################
    postgres:
        image: postgres:15.2-alpine
        ports:
            - "5432:5432"
        volumes:
            - ./pg-init-scripts:/docker-entrypoint-initdb.d
            - ./volumes/postgresql:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_MULTIPLE_DATABASES=sampledb
        healthcheck: 
            interval: 10s
            retries: 10
            test: "pg_isready -U \"$$POSTGRES_USER\" -d \"sampledb\""
            timeout: 2s      
        networks:
            - sqlmodel-example

networks:
    sqlmodel-example: